CREATE TABLE `kotel` (
  `DEST_TP` float DEFAULT NULL,
  `DEST_TO` float DEFAULT NULL,
  `DEST_KW` int(11) DEFAULT NULL,
  `DEST_TC` float DEFAULT NULL,
  `TP` float DEFAULT NULL,
  `KW` int(11) DEFAULT NULL,
  `PR` float DEFAULT NULL,
  `DEVICE_ID` varchar(100) NOT NULL,
  `TO` float NOT NULL DEFAULT '0',
  `DEST_PR` float NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
